/**
 * Daily dispatch - generates and sends garden conversations
 *
 * For each unique location_key+author combination with active subscribers:
 * 1. Spawn Python engine subprocess to generate prose
 * 2. Store result in daily_runs
 * 3. Email all matching active, confirmed subscribers
 */

const { spawn } = require('child_process');
const { v4: uuidv4 } = require('uuid');
const path = require('path');
const fs = require('fs');
const { sendDailyEmail } = require('../services/email');
const { getSeasonName } = require('../services/seasonNames');
const { detectWeatherType } = require('../services/weather');
const { getSubRegion, getSubRegionFlavor } = require('../services/sub-regions');

const MASTHEAD_DIR = path.join(__dirname, '..', '..', 'data', 'mastheads');
const MASTHEAD_SCRIPT = path.join(__dirname, '..', 'services', 'generate_masthead.py');
const TITLE_SCRIPT   = path.join(__dirname, '..', 'services', 'generate_title.py');
const APP_URL = process.env.APP_URL || 'https://theplotline.net';

// ── Solar term lookup (matches garden_seasons.py exactly) ────────────────────
// Returns the current solar term name for a given Date (defaults to today).
const SOLAR_TERMS_JS = [
  { month: 2,  day: 4,  name: 'Beginning of Spring' },
  { month: 2,  day: 19, name: 'Rain Water'           },
  { month: 3,  day: 6,  name: 'Awakening of Insects' },
  { month: 3,  day: 21, name: 'Spring Equinox'       },
  { month: 4,  day: 5,  name: 'Pure Brightness'      },
  { month: 4,  day: 20, name: 'Grain Rain'           },
  { month: 5,  day: 6,  name: 'Beginning of Summer'  },
  { month: 5,  day: 21, name: 'Grain Buds'           },
  { month: 6,  day: 6,  name: 'Grain in Ear'         },
  { month: 6,  day: 21, name: 'Summer Solstice'      },
  { month: 7,  day: 7,  name: 'Minor Heat'           },
  { month: 7,  day: 23, name: 'Major Heat'           },
  { month: 8,  day: 8,  name: 'Beginning of Autumn'  },
  { month: 8,  day: 23, name: 'End of Heat'          },
  { month: 9,  day: 8,  name: 'White Dew'            },
  { month: 9,  day: 23, name: 'Autumn Equinox'       },
  { month: 10, day: 8,  name: 'Cold Dew'             },
  { month: 10, day: 23, name: "Frost's Descent"      },
  { month: 11, day: 7,  name: 'Beginning of Winter'  },
  { month: 11, day: 22, name: 'Minor Snow'           },
  { month: 12, day: 7,  name: 'Major Snow'           },
  { month: 12, day: 22, name: 'Winter Solstice'      },
  { month: 1,  day: 6,  name: 'Minor Cold'           },
  { month: 1,  day: 20, name: 'Major Cold'           },
];

function getCurrentSolarTerm(date = new Date()) {
  const m = date.getMonth() + 1; // 1-indexed
  const d = date.getDate();
  // Walk backwards through terms to find the most recent one
  // Build a flat list sorted by (month, day), handling Jan wrap
  const sorted = [...SOLAR_TERMS_JS].sort((a, b) => {
    const am = a.month === 1 ? 13 : a.month;
    const bm = b.month === 1 ? 13 : b.month;
    if (am !== bm) return am - bm;
    return a.day - b.day;
  });
  const cm = m === 1 ? 13 : m;
  let current = sorted[sorted.length - 1]; // default: last of year
  for (const term of sorted) {
    const tm = term.month === 1 ? 13 : term.month;
    if (tm < cm || (tm === cm && term.day <= d)) {
      current = term;
    }
  }
  return current.name;
}

/**
 * Get or generate a masthead image for a combo + run.
 * Returns a public URL string, or null on failure.
 */
async function getMasthead(combo, dailyRun) {
  const station = combo.station_code || combo.location_key || 'UNK';
  const author = combo.author_key || 'hemingway';
  const season = (dailyRun.season || 'spring').toLowerCase();
  const weatherType = detectWeatherType(dailyRun.weather_summary || '');
  const solarTerm = getCurrentSolarTerm();
  // Title is pre-generated by getNewsletterTitle(); pass it to the art renderer
  const title = dailyRun.newsletter_title || null;

  // Include solar term in filename so caches per-term automatically
  const termSlug = solarTerm.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  const filename = `${station}-${author}-${season}-${weatherType}-${termSlug}.png`;
  const filepath = path.join(MASTHEAD_DIR, filename);

  // Return cached if exists
  if (fs.existsSync(filepath)) {
    return `${APP_URL}/mastheads/${filename}`;
  }

  // Generate
  return new Promise((resolve) => {
    const mastheadArgs = [
      MASTHEAD_SCRIPT, station, author, season, weatherType,
      '--output', filepath,
      '--solar-term', solarTerm,
    ];
    if (title) mastheadArgs.push('--title', title);
    const proc = spawn('python3', mastheadArgs, { timeout: 15000 });

    proc.on('close', (code) => {
      if (code === 0 && fs.existsSync(filepath)) {
        resolve(`${APP_URL}/mastheads/${filename}`);
      } else {
        console.warn(`[masthead] Generation failed for ${filename} (code ${code})`);
        resolve(null);
      }
    });

    proc.on('error', (err) => {
      console.warn(`[masthead] spawn error: ${err.message}`);
      resolve(null);
    });
  });
}

/**
 * Generate a folksy newsletter title via generate_title.py (phi4 → static fallback).
 * Returns a plain string — the title. Never throws.
 *
 * @param {string} solarTerm  - e.g. "Rain Water"
 * @param {string} season     - e.g. "spring"
 * @param {string} weatherType - e.g. "rainy"
 * @param {string} [region]   - e.g. "high_plains"
 */
function getNewsletterTitle(solarTerm, season, weatherType, region) {
  return new Promise((resolve) => {
    const args = ['python3', TITLE_SCRIPT,
      '--output-json',
      '--solar-term', solarTerm,
      '--season',     season,
      '--weather',    weatherType,
    ];
    if (region) args.push('--region', region);

    const proc = spawn(args[0], args.slice(1), { timeout: 20000 });
    let out = '';
    proc.stdout.on('data', d => { out += d.toString(); });
    proc.on('close', (code) => {
      try {
        const parsed = JSON.parse(out.trim());
        console.log(`[title] "${parsed.title}" (source: ${parsed.source})`);
        resolve(parsed.title || 'Plot Lines');
      } catch {
        // Plain text fallback (no --output-json or parse error)
        const plain = out.trim().splitlines?.()?.[0] || out.trim();
        resolve(plain || 'Plot Lines');
      }
    });
    proc.on('error', (err) => {
      console.warn(`[title] spawn error: ${err.message}`);
      resolve('Plot Lines');
    });
  });
}

const PYTHON_PATH = process.env.PYTHON_PATH || 'python3';
const ENGINE_PATH = path.join(__dirname, '..', 'garden', 'engine.py');

/**
 * Get author-voiced season name for a daily run
 * Returns the name, or null if not available
 */
async function getAuthorSeasonName(dailyRun, combo, db) {
  if (!dailyRun.micro_season_id || !combo.climate_zone_id) {
    return null;
  }

  try {
    // Get season number from micro_season_id
    const microSeason = await db.prepare(`
      SELECT season_number FROM micro_seasons WHERE id = ?
    `).get(dailyRun.micro_season_id);

    if (!microSeason) {
      console.warn(`[dispatch] Micro season not found: ${dailyRun.micro_season_id}`);
      return null;
    }

    // Get author-voiced season name
    const seasonName = await getSeasonName(
      combo.climate_zone_id,
      combo.author_key,
      microSeason.season_number,
      db
    );

    return seasonName;
  } catch (err) {
    console.warn(`[dispatch] Failed to get author season name:`, err.message);
    return null;
  }
}

/**
 * Get today's date in YYYY-MM-DD format
 */
function getToday() {
  return new Date().toISOString().split('T')[0];
}

/**
 * Run the Python garden engine for a combination
 * @param {object} combo - combination row
 * @returns {Promise<object>} - parsed JSON result
 */
function runEngine(combo) {
  return new Promise((resolve, reject) => {
    const args = [
      ENGINE_PATH,
      '--station', combo.station_code || combo.location_key,
      '--author', combo.author_key,
      '--city', combo.location_city || 'Unknown',
      '--state', combo.location_state || 'Unknown',
      '--lat', String(combo.lat || 39.7392),
      '--lon', String(combo.lon || -104.9903),
      '--context', combo.garden_context || '',
      '--sub-region', (() => {
        const id = getSubRegion(combo.station_code, combo.lat, combo.lon);
        return id ? (getSubRegionFlavor(id) || '') : '';
      })(),
      '--output', 'json'
    ];

    console.log(`[dispatch] Running engine: ${PYTHON_PATH} ${args.join(' ')}`);

    const proc = spawn(PYTHON_PATH, args, {
      cwd: path.dirname(ENGINE_PATH),
      timeout: 120000 // 2 minute timeout
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => {
      stdout += data.toString();
    });

    proc.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('close', (code) => {
      if (code !== 0) {
        console.error(`[dispatch] Engine failed with code ${code}`);
        console.error(`[dispatch] stderr: ${stderr}`);
        reject(new Error(`Engine exited with code ${code}: ${stderr}`));
        return;
      }

      try {
        const result = JSON.parse(stdout);
        resolve(result);
      } catch (err) {
        console.error(`[dispatch] Failed to parse engine output: ${stdout}`);
        reject(new Error(`Invalid engine output: ${err.message}`));
      }
    });

    proc.on('error', (err) => {
      reject(err);
    });
  });
}

/**
 * Main dispatch function - run daily
 * @param {object} db - database wrapper (fastify.db or standalone Pool wrapper)
 */
async function runDispatch(db) {
  // If no db passed (standalone mode), create one
  if (!db) {
    const { Pool } = require('pg');
    if (!process.env.DATABASE_URL) {
      throw new Error('DATABASE_URL environment variable is required');
    }
    const pool = new Pool({ connectionString: process.env.DATABASE_URL });
    db = {
      prepare: (sql) => {
        let paramIndex = 0;
        const pgSql = sql.replace(/\?/g, () => `$${++paramIndex}`);
        return {
          run: (...params) => pool.query(pgSql, params),
          get: async (...params) => {
            const result = await pool.query(pgSql, params);
            return result.rows[0];
          },
          all: async (...params) => {
            const result = await pool.query(pgSql, params);
            return result.rows;
          },
        };
      },
      close: () => pool.end(),
    };
  }

  const today = getToday();
  console.log(`[dispatch] Starting daily dispatch for ${today}`);

  try {
    // Get all combinations that have active, confirmed subscribers
    const combinations = await db.prepare(`
      SELECT DISTINCT c.*
      FROM combinations c
      INNER JOIN subscribers s ON s.author_key = c.author_key
        AND (
          (s.station_code = c.station_code AND c.station_code IS NOT NULL) OR
          (ROUND(s.lat * 20) / 20 = ROUND(c.lat * 20) / 20 AND
           ROUND(s.lon * 20) / 20 = ROUND(c.lon * 20) / 20)
        )
      WHERE s.active = 1 AND s.confirmed_at IS NOT NULL
    `).all();

    console.log(`[dispatch] Found ${combinations.length} active combinations`);

    for (const combo of combinations) {
      // Check if we already have a run for today
      const existingRun = await db.prepare(`
        SELECT id, status FROM daily_runs
        WHERE combination_id = ? AND run_date = ?
      `).get(combo.id, today);

      if (existingRun && existingRun.status === 'completed') {
        console.log(`[dispatch] Already completed: ${combo.location_key}/${combo.author_key}`);
        continue;
      }

      console.log(`[dispatch] Processing: ${combo.location_key}/${combo.author_key}`);

      const startTime = Date.now();

      try {
        // Run engine
        const result = await runEngine(combo);
        const generationMs = Date.now() - startTime;

        // Create or update daily run
        const runId = existingRun?.id || uuidv4();

        if (existingRun) {
          await db.prepare(`
            UPDATE daily_runs
            SET status = 'completed',
                prose_text = ?, prose_html = ?, topic = ?, quote = ?,
                author_name = ?, weather_summary = ?, characters = ?,
                generated_at = NOW(), generation_ms = ?
            WHERE id = ?
          `).run(
            result.prose_text, result.prose_html, result.topic, result.quote,
            result.author_name, result.weather_summary, result.characters?.join(', '),
            generationMs, runId
          );
        } else {
          await db.prepare(`
            INSERT INTO daily_runs (
              id, combination_id, run_date, status,
              prose_text, prose_html, topic, quote,
              author_name, weather_summary, characters,
              generated_at, generation_ms
            ) VALUES (?, ?, ?, 'completed', ?, ?, ?, ?, ?, ?, ?, NOW(), ?)
          `).run(
            runId, combo.id, today,
            result.prose_text, result.prose_html, result.topic, result.quote,
            result.author_name, result.weather_summary, result.characters?.join(', '),
            generationMs
          );
        }

        console.log(`[dispatch] Generated in ${generationMs}ms: ${combo.location_key}/${combo.author_key}`);

        // Get subscribers for this combination
        const subscribers = await db.prepare(`
          SELECT id, email, unsubscribe_token
          FROM subscribers
          WHERE author_key = ?
            AND (
              (station_code = ? AND station_code IS NOT NULL) OR
              (ROUND(lat * 20) / 20 = ROUND(?) / 20 AND
               ROUND(lon * 20) / 20 = ROUND(?) / 20)
            )
            AND active = 1 AND confirmed_at IS NOT NULL
        `).all(combo.author_key, combo.station_code, combo.lat, combo.lon);

        console.log(`[dispatch] Sending to ${subscribers.length} subscribers`);

        // Get the run for email
        const dailyRun = await db.prepare('SELECT * FROM daily_runs WHERE id = ?').get(runId);

        // Attach author-voiced season name if available
        const authorSeasonName = await getAuthorSeasonName(dailyRun, combo, db);
        if (authorSeasonName) {
          dailyRun.author_season_name = authorSeasonName;
        }

        // Generate newsletter title (folksy, phi4-driven)
        const season      = (dailyRun.season || 'spring').toLowerCase();
        const weatherType = detectWeatherType(dailyRun.weather_summary || '');
        const solarTerm   = getCurrentSolarTerm();
        const region      = combo.climate_zone_slug || null;
        dailyRun.newsletter_title = await getNewsletterTitle(solarTerm, season, weatherType, region);

        // Generate masthead (lazy, cached) — passes title into art layer
        const mastheadUrl = await getMasthead(combo, dailyRun);
        if (mastheadUrl) {
          dailyRun.masthead_url = mastheadUrl;
          console.log(`[dispatch] Masthead: ${mastheadUrl}`);
        }

        // Send emails
        for (const sub of subscribers) {
          try {
            await sendDailyEmail(sub.email, dailyRun, sub.unsubscribe_token);

            // Record delivery
            await db.prepare(`
              INSERT INTO deliveries (id, daily_run_id, subscriber_id, status, sent_at)
              VALUES (?, ?, ?, 'sent', NOW())
            `).run(uuidv4(), runId, sub.id);

            console.log(`[dispatch] Sent to ${sub.email}`);

          } catch (emailErr) {
            console.error(`[dispatch] Email failed for ${sub.email}:`, emailErr.message);

            await db.prepare(`
              INSERT INTO deliveries (id, daily_run_id, subscriber_id, status, error)
              VALUES (?, ?, ?, 'failed', ?)
            `).run(uuidv4(), runId, sub.id, emailErr.message);
          }
        }

      } catch (engineErr) {
        console.error(`[dispatch] Engine failed for ${combo.location_key}/${combo.author_key}:`, engineErr.message);

        // Record failed run
        if (!existingRun) {
          await db.prepare(`
            INSERT INTO daily_runs (id, combination_id, run_date, status)
            VALUES (?, ?, ?, 'failed')
          `).run(uuidv4(), combo.id, today);
        } else {
          await db.prepare(`UPDATE daily_runs SET status = 'failed' WHERE id = ?`).run(existingRun.id);
        }
      }
    }

    console.log(`[dispatch] Completed daily dispatch for ${today}`);

  } catch (err) {
    console.error('[dispatch] Fatal error:', err);
  }
}

// Export for cron
module.exports = { runDispatch };

// Run directly if called as script
if (require.main === module) {
  require('dotenv').config({ path: require('path').join(__dirname, '..', '..', '.env') });
  runDispatch().then(() => {
    console.log('[dispatch] Done');
    process.exit(0);
  }).catch(err => {
    console.error('[dispatch] Error:', err);
    process.exit(1);
  });
}
