module.exports = {
  apps: [
    {
      name: 'thread',
      script: 'server/index.js',
      cwd: '/opt/thread',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        HOST: '127.0.0.1',
        DATABASE_URL: 'SET_VIA_ENV',
        IMAGE_STORAGE_PATH: '/data/images',
        GEMINI_MODEL: 'gemini-2.5-flash',
        OLLAMA_BASE_URL: 'http://localhost:11434',
        DEFAULT_VISION_MODEL: 'llava:7b',
        DEFAULT_TEXT_MODEL: 'llama3.2:3b',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/data/logs/thread-error.log',
      out_file: '/data/logs/thread-out.log',
    },
    {
      name: 'plotlines',
      script: 'server/index.js',
      cwd: '/opt/plotlines',
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
        HOST: '127.0.0.1',
        DATABASE_PATH: '/opt/plotlines/data/plotlines.db',
        CLIENT_URL: 'https://theplotline.net',
        BASE_URL: 'https://theplotline.net',
        SMTP_HOST: 'smtp.resend.com',
        SMTP_PORT: '465',
        SMTP_USER: 'resend',
        SMTP_PASS: 'SET_VIA_ENV',
        SMTP_FROM: 'garden@theplotline.net',
        ADMIN_PASSWORD: 'SET_VIA_ENV',
        ADMIN_SECRET: 'SET_VIA_ENV',
        STRIPE_PUBLISHABLE_KEY: 'SET_VIA_ENV',
        STRIPE_SECRET_KEY: 'SET_VIA_ENV',
        STRIPE_WEBHOOK_SECRET: 'SET_VIA_ENV',
        STRIPE_PRODUCT_ID: 'prod_U4X8x6Uouh2QAO',
        STRIPE_PRICE_WEEKLY: 'price_1T6O428OA2NW5jQ16JctMJER',
        STRIPE_PRICE_MONTHLY: 'price_1T6O428OA2NW5jQ1R3ddq4Kv',
        STRIPE_BETA_COUPON_ID: 'z3TAEuwH',
        STRIPE_COUPON_FREE_MONTH: 'z3TAEuwH',
        TURNSTILE_SITE_KEY: 'SET_VIA_ENV',
        TURNSTILE_SECRET_KEY: 'SET_VIA_ENV',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: '300M',
      error_file: '/data/logs/plotlines-error.log',
      out_file: '/data/logs/plotlines-out.log',
    }
  ]
}
